[package]
name = "ft_api"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util"}
serde = { version = "1.0.197", features = ["derive"]}
serde_json = { version = "1.0.115", features = [ "std"] }
reqwest = { version = "0.12.3" , features = ["json"] }
tokio = { version = "1.37.0", features = ["rt", "macros","rt-multi-thread" ] }
chrono = "0.4.37"
