[package]
name = "ft_api"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util"}
serde = { version = "1.0.197"}
serde_json="1.0.115"
reqwest = { version = "0.12.3" , features = ["json"] }
