[package]
name = "libft-api-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.106", features = ["full"]}
quote = "1.0.41"
proc-macro2 = "1.0.101"
